name: Checks

on:
  push:
    branches: [main, '*.x']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: mozex/reusable-workflows/.github/workflows/code-styling.yml@c2b1a0f19759007a1703b936bd0ce68cac90533b # main
    with:
      php_version: '8.5'
      test_mode: true

  types:
    name: Types
    uses: mozex/reusable-workflows/.github/workflows/code-analysis.yml@c2b1a0f19759007a1703b936bd0ce68cac90533b # main
    with:
      php_version: '8.5'

  type-coverage:
    name: Type Coverage
    uses: mozex/reusable-workflows/.github/workflows/type-coverage.yml@c2b1a0f19759007a1703b936bd0ce68cac90533b # main
    with:
      php_version: '8.5'
      phpunit_config_file: 'phpunit.xml.dist'
      min: 100

  tests:
    name: Tests P${{ matrix.php }} - L${{ matrix.laravel }} - F${{ matrix.filament }} - ${{ matrix.dependency-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4, 8.5]
        laravel: [13.*, 12.*, 11.*]
        filament: ["^3.3.0", "^4.11.0"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: "11.*"
            testbench: "^9.2"
            carbon: "^3.8.4"
          - laravel: "12.*"
            testbench: "10.*"
            carbon: "^3.8.4"
          - laravel: "13.*"
            testbench: "^11.0"
            carbon: "^3.8.4"
        exclude:
          - laravel: "13.*"
            filament: "^3.3.0"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip, fileinfo, intl
          coverage: none

      - name: Require dependencies
        run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" "filament/filament:${{ matrix.filament }}" --no-interaction --no-update

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

      - name: Tests
        run: vendor/bin/pest --colors=always
